AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the ACS Parts Inventory Application

Resources:
  DatabaseStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/acs-parts-inventory/stacks/database.yaml'

  LambdasStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/acs-parts-inventory/stacks/lambdas.yaml'
    DependsOn: DatabaseStack
