AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DatabaseStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/acs-parts-inventory/stacks/database.yaml'

  LambdasStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/acs-parts-inventory/stacks/lambdas.yaml'
    DependsOn: DatabaseStack

  WebsiteStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/acs-parts-inventory/stacks/website.yaml'
    DeletionPolicy: Retain
    DependsOn: LambdasStack
