AWSTemplateFormatVersion: '2010-09-09'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'acs-parts-inventory-gui-${AWS::Region}'

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/index.html'

  S3BucketWebsiteConfiguration:
    Type: 'AWS::S3::Bucket'
    DependsOn: S3BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      WebsiteConfiguration:
        IndexDocument: index.html

  S3Object:
    Type: 'AWS::S3::Object'
    DependsOn: S3BucketWebsiteConfiguration
    Properties:
      Bucket: !Ref S3Bucket
      Key: index.html
      Source: index.html
      ContentType: text/html

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL of the static website
